name: sueltito
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  intl: ^0.20.2
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  flutter_riverpod: ^2.4.0
  device_info_plus: ^10.1.0
  geolocator: ^11.0.0
  flutter_dotenv: ^5.1.0
  go_router: ^14.2.0
  flutter_nfc_kit: ^3.3.2
  permission_handler: ^11.2.0
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_with_text.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
